[package]
name = "cliente"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modulos_comunes = { path = "../modulos_comunes" }
macroquad = "0.3.23"
load_file = "1.0.1"
quad-gif = "0.2.0"
